### ISSUE TITLE
OSS License for laravel-stream

### ISSUE THREAD

**Issue by iljalukin** [waleedahmad/laravel-stream#2]
Dear Waleed,

I appreciate your work and would like to thank you for your tutorial concerning video transcoding with laravel queues. 
I also wanted to ask you to add an open-source license to your laravel-stream project on Github (e.g. MIT license), so that forking of the project and using parts of it would be explicitly allowed and legal for other users.

Thank you in advance
Ilja

**Comment by waleedahmad** [comment]
I'll add MIT license to the repository. Thanks for pointing it out.

**Comment by waleedahmad** [comment]
Added in https://github.com/waleedahmad/laravel-stream/commit/6a6a6e26cd7c0733a378076e06c6762a3892b522
